CREATE TABLE [dbo].[Person]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY(1, 1),
	[Guid] UNIQUEIDENTIFIER UNIQUE NOT NULL,
	[FirstName] VARCHAR(100) NOT NULL,
	[LastName] VARCHAR(100) NOT NULL,
	[PhoneNumber] VARCHAR(15) NOT NULL,
	[EmailAddress] VARCHAR(100) NOT NULL
)
